### ISSUE TITLE
autosave error

### ISSUE THREAD

**Issue by jingliinpurdue** [lijunzh/dotfiles#1]
<img width="712" alt="Screen Shot 2022-07-31 at 10 10 53 AM" src="https://user-images.githubusercontent.com/36382883/182034490-1d782234-ea3c-4532-b5c2-ee86609baab0.png">

**Comment by lijunzh** [comment]
@jingliinpurdue , could you please run the following commends to remove existing NeoVim installation and try again?

```sh
rm -rf .config/nvim .local/share/nvim/
```

**Comment by lijunzh** [comment]
@jingliinpurdue Bug is confirmed. Will be working on a solution soon.
